server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.230.197:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1eh76n999e95c37so.mysql.rds.aliyuncs.com:3306/guli_pms
    username: home
    password: qq654321
  redis:
    host: 47.107.230.197
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml